name: wapp
description: "weather application"
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  lottie: ^2.2.0
  shared_preferences: ^2.1.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  assets:
    - assets/lottie/
